### ISSUE TITLE
Bug report: Swagger UI not working

### ISSUE THREAD

**Issue by weslambert** [gchq/CyberChef-server#5]
**Describe the bug**
When viewing `http://localhost:3000` or `http://$host:3000`, the page is blank, and errors are noticed in Chrome Dev tools.  The underlying server seems to work fine and respond to requests -- it's just the Swagger docs that are unviewable.

**To Reproduce**
Follow documented instructions to run CyberChef-server from the README ( I actually had to perform an `npm run prod` vs `npm run` to start the project).

**Expected behavior**
Swagger documentation is displayed.

**Node version:**
10.18.1

**Additional context**
I'm not seeing any CSS files in the CyberChef-server folder.  I'm not terribly familiar with Node, so please forgive my ignorance with regard to how things are built/managed.

![image](https://user-images.githubusercontent.com/16829864/72395857-d7529100-3708-11ea-8344-0be6c0bca204.png)

**Comment by d98762625** [comment]
Confirmed that I can replicate this behaviour

**Comment by d98762625** [comment]
@weslambert note that `npm run` won't work, but `npm run start` would. `npm run` needs a script name to run.
